using VerifyCS = NpgsqlSourceGenerators.Tests.Verifiers.IncrementalGeneratorVerifier<NpgSqlSourceGenerator.NpgsqlEnumIncrementalSourceGenerator>;

namespace NpgsqlSourceGenerators.Tests;

public class UnitTest1
{
    [Fact]
    public async Task GeneratesAttribute()
    {
        const string code = "";

        const string expected = """
                                // <auto-generated/>
                                #nullable enable
                                namespace NpgSqlGenerators;
                                [System.AttributeUsage(System.AttributeTargets.Enum)]
                                public class PostgresEnumAttribute : System.Attribute
                                {
                                    public string? Name { get; set; }
                                }
                                """;

        await VerifyCS.VerifyGeneratorAsync(code, ("PostgresEnumAttribute.g.cs", expected));
    }
}