using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace NpgSqlSourceGenerator;

/// <summary>
/// A sample source generator that creates a custom report based on class properties. The target class should be annotated with the 'Generators.ReportAttribute' attribute.
/// When using the source code as a baseline, an incremental source generator is preferable because it reduces the performance overhead.
/// </summary>
[Generator]
public class NpgsqlEnumIncrementalSourceGenerator : IIncrementalGenerator
{
	private const string Namespace = "NpgSqlGenerators";
	private const string AttributeName = "PostgresEnumAttribute";

	private const string AttributeSourceCode = $$"""
	    // <auto-generated/>
	    #nullable enable
	    namespace {{Namespace}};
	                                             
	    [System.AttributeUsage(System.AttributeTargets.Enum)]
	    public class {{AttributeName}} : System.Attribute
	    {
	        public string? Name { get; set; }
	    }
	    """;

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// Add the marker attribute to the compilation.
		context.RegisterPostInitializationOutput(ctx => ctx.AddSource(
			"PostgresEnumAttribute.g.cs",
			SourceText.From(AttributeSourceCode, Encoding.UTF8)));

		var p = context.SyntaxProvider.ForAttributeWithMetadataName(
			 $"{Namespace}.{AttributeName}",
			 (sn, _) => sn is EnumDeclarationSyntax,
			 (gasc, _) => (Namespace: gasc.TargetSymbol.ContainingNamespace.ToDisplayString(), gasc.TargetSymbol.Name)
		);

		// Generate the source code.
		context.RegisterSourceOutput(p.Collect(), GenerateCode);
	}


	/// <summary>
	/// Generate code action.
	/// It will be executed on specific nodes (ClassDeclarationSyntax annotated with the [Report] attribute) changed by the user.
	/// </summary>
	/// <param name="context">Source generation context used to add source files.</param>
	/// <param name="enumDeclarations">Nodes annotated with the [Report] attribute that trigger the generate action.</param>
	private static void GenerateCode(SourceProductionContext context, ImmutableArray<(string Namespace, string Name)> enumDeclarations)
	{

		var code = $$"""
		    // <auto-generated/>
		    #nullable enable
		    using Npgsql;
		    using Microsoft.EntityFrameworkCore;
		           
		    namespace {{Namespace}};
		           
		    internal static class PostgresEnumHelpers
		    {
		        public static NpgsqlDataSourceBuilder MapPostgresEnums(this NpgsqlDataSourceBuilder builder)
		        {
		            {{string.Join("\n    ", enumDeclarations.Select(m => $"builder.MapEnum<{m.Namespace}.{m.Name}>();"))}}
		            return builder;
		        }

		        public static void RegisterPostgresEnums(this ModelBuilder builder)
		        {
		            {{string.Join("\n    ", enumDeclarations.Select(m => $"builder.HasPostgresEnum<{m.Namespace}.{m.Name}>();"))}}
		        }
		    }
		    """;
		
		context.AddSource("PostgresEnumHelpers.g.cs", SourceText.From(code, Encoding.UTF8));
	}
}